### ISSUE TITLE
Je gebruikt een config array die niet bestaat in db_config.php

### ISSUE THREAD

**Issue by hiddebraun-ma** [imcrazydia/MyBand#2]
https://github.com/imcrazydia/MyBand/blob/1e88c3c7d18e867c782fe0c87ff18b5be7b82c45/private/includes/functions.php#L10-L12

Kijk eens goed:
In je `db_config.php` bestand gebruik je een `define` en definieer je dus constanten (DB_SERVER, DB_NAME etc). 
Maar in deze code doe je de aanname dat er een array is teruggekomen via `require db_config.php`
Maar dat is niet zo, er staat geen `return $config;` in `db_config.php`. Snap je?

Daarom wordt de verbinding al niet goed en gaat de code die je daarna op de PDO verbinding uitvoert niet goed.

Dus gebruik in je open_connection() OF de constanten (DB_NAME, DB_USER etc.) OF maak in db_config.php een array die je met een return teruggeeft, zoals hier bij Opdracht 2:
http://mamd.sites.ma-cloud.nl/bap-7a-private-public-folders-code-organisatie/

**Comment by imcrazydia** [comment]
Hij werkt nu. Dankjewel

Sent from Mail for Windows 10

From: Hidde Braun
Sent: Tuesday, 4 June 2019 12:35
To: imcrazydia/MyBand
Cc: Subscribed
Subject: [imcrazydia/MyBand] Je gebruikt een config array die niet bestaat indb_config.php (#2)

https://github.com/imcrazydia/MyBand/blob/1e88c3c7d18e867c782fe0c87ff18b5be7b82c45/private/includes/functions.php#L10-L12
Kijk eens goed:
In je db_config.php bestand gebruik je een define en definieer je dus constanten (DB_SERVER, DB_NAME etc).
Maar in deze code doe je de aanname dat er een array is teruggekomen via require db_config.php
Maar dat is niet zo, er staat geen return $config; in db_config.php. Snap je?
Daarom wordt de verbinding al niet goed en gaat de code die je daarna op de PDO verbinding uitvoert niet goed.
Dus gebruik in je open_connection() OF de constanten (DB_NAME, DB_USER etc.) OF maak in db_config.php een array die je met een return teruggeeft, zoals hier bij Opdracht 2:
http://mamd.sites.ma-cloud.nl/bap-7a-private-public-folders-code-organisatie/

**Comment by hiddebraun-ma** [comment]
Cool!
________________________________
